version: "3"
services:
  app:
    build: ./.devcontainer/containers/app/
    tty: true
    volumes:
      - .:/go/src/gin_tutorial
    ports:
      - 8080:8080

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: blog
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postagresql/data

volumes:
  database:
