version: "3"
services:
  app:
    build: 
      context: .
      dockerfile: ./.devcontainer/containers/app/Dockerfile
      args:
        USER_UID: $USER_UID
        USER_GID: $USER_GID
        USERNAME: $USER
    tty: true
    volumes:
      - .:/go/src/gin_tutorial
    ports:
      - 8080:8080
    user: "${USER_UID}:${USER_GID}"

  db:
    image: postgres:10
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
      POSTGRES_DB: blog
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postagresql/data

volumes:
  database:
